### ISSUE TITLE
Release 0.1.0 Checklist

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#1]
In order to release the first version (0.1.0) here you may find the relevant checklist:

- [x] Setup linter (remember to include the linting passage before building)
- [x] Prepare Dockerfile
- [x] Prepare CI/CD environment
- [x] Populate README with deployment instructions
- [x] Bump version number in config files
- [x] Tag the last git commit with the version number
@alranel

**Comment by libremente** [comment]
Done, closing.
